[build]
builder = "NIXPACKS"
nixpacksConfigPath = "railway.build.toml"
# buildCommand = "pnpm build"
# buildEnvironment = "V2"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
region = "us-west2"
# multiRegionConfig = {"us-east4-eqdc4a":{"numReplicas":1}}
# startCommand = "pnpm start"
