import type { TattooItemProps } from './types'

export const mockTattooItems: TattooItemProps[] = [
  {
    id: '1',
    name: 'Japanese Dragon Sleeve',
    category: 'arm',
    createdAt: new Date('2024-01-15'),
    htmlDescription: null,
    userId: 'artist-sarah',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Full sleeve dragon design with traditional Japanese elements',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '2',
    name: 'Minimalist Wrist Compass',
    category: 'wrist',
    createdAt: new Date('2024-02-01'),
    htmlDescription: null,
    userId: 'artist-mike',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Simple geometric compass design for inner wrist',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '3',
    name: 'Phoenix Back Piece',
    category: 'back',
    createdAt: new Date('2024-02-15'),
    htmlDescription: null,
    userId: 'artist-james',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Large-scale phoenix design covering full back',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '4',
    name: 'Floral Cover-Up Shoulder',
    category: 'cover-up',
    createdAt: new Date('2024-03-01'),
    htmlDescription: null,
    userId: 'artist-lisa',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Peony and cherry blossom design covering old tattoo',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '5',
    name: 'Geometric Chest Piece',
    category: 'chest',
    createdAt: new Date('2024-03-15'),
    htmlDescription: null,
    userId: 'artist-david',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Sacred geometry mandala chest tattoo',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '6',
    name: 'Fine Line Finger Rings',
    category: 'finger',
    createdAt: new Date('2024-03-20'),
    htmlDescription: null,
    userId: 'artist-emma',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Delicate line work finger tattoo set',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '7',
    name: 'Traditional Snake Leg Sleeve',
    category: 'leg',
    createdAt: new Date('2024-03-25'),
    htmlDescription: null,
    userId: 'artist-tom',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Full leg sleeve with traditional snake design',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '8',
    name: 'Script Neck Piece',
    category: 'neck',
    createdAt: new Date('2024-04-01'),
    htmlDescription: null,
    userId: 'artist-anna',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Elegant calligraphy script design for neck',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '9',
    name: 'Tribal Full Body Suite',
    category: 'full-body',
    createdAt: new Date('2024-04-05'),
    htmlDescription: null,
    userId: 'artist-ray',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Traditional Polynesian full body tattoo design',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  },
  {
    id: '10',
    name: 'Connected Nature Sleeve',
    category: 'connected-pieces',
    createdAt: new Date('2024-04-10'),
    htmlDescription: null,
    userId: 'artist-kate',
    thumbnail: 'https://picsum.photos/200/300',
    description: 'Nature-themed connected pieces from shoulder to wrist',
    privacy: 'PUBLIC',
    jsonDescription: null,
    gallery: ['https://picsum.photos/200/300']
  }
]
